config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'application#hello'


  resources :dashboards, :only =>[:index]

  resources :incomes, :only =>[:index, :new, :create]
  resources :expenditures, :only =>[:index, :new, :create]
  resources :goals, :only =>[:index, :new, :create]
  resources :projections, :only =>[:index, :new, :create]


  root 'static_pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord

  validates :amount, presence: true, numericality: { only_integer: true }

  belongs_to :user

    validates :name, :presence => true
    validates :amount, :presence => true
    validates :date, :presence => true


end

app/models/goal.rb
class Goal < ApplicationRecord

  validates :amount, presence: true,numericality: { only_integer: true }

  belongs_to :user

  validates :name, :presence => true
  validates :amount, :presence => true
  validates :start_date, :presence => true
  validates :target_date, :presence => true
end

app/models/income.rb
class Income < ApplicationRecord

  validates :amount, presence: true,numericality: { only_integer: true }

  belongs_to :user

  validates :name, :presence => true
  validates :amount, :presence => true
  validates :date, :presence => true

end

app/models/projection.rb
class Projection < ApplicationRecord
  belongs_to :user
  validates :start_date, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :incomes, dependent: :destroy
  has_many :expenditures, dependent: :destroy
  has_many :projections
  has_many :goals




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render text: "hello, world!!"
  end

  def after_sign_in_path_for(resource)
    dashboards_path
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  before_action :authenticate_user!

  def index
    @dashboard = Dashboard.new(current_user)

    @income = @dashboard.get_income

    if no_record_stored(@income)
      flash[:notice] = 'No incomes stored'
    else
      @income
    end

    @expenditure = @dashboard.get_expenditure

    if no_record_stored(@expenditure)
      flash[:notice] = 'No expenditure stored'
    else
      @expenditure
    end

    @projection = @dashboard.get_projection

    if no_record_stored(@projection)
      flash[:notice] = 'No projection stored'
    else
      @projection
    end

    @goal = @dashboard.get_goal

    if no_record_stored(@goal)
      flash[:notice] = 'No goal stored'
    else
      @goal
    end

  end

private

  def no_record_stored(record)
    record == []
  end

end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController

  before_action :authenticate_user!

  def index

    @expenditure_data = Expenditure.where(user_id: current_user.id)

    respond_to do |format|
      format.html
      format.json { render json: @expenditure_data }
    end

  end

  def new
    @expenditure = Expenditure.new
  end

  def create
    current_user.expenditures.create(expenditure_params)
    redirect_to dashboards_path
  end

  private

  def expenditure_params
    params.require(:expenditure).permit(:amount, :name, :date)
  end


end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :authenticate_user!

    def index

      @goal_data = Goal.where(user_id: current_user.id)

      respond_to do |format|
        format.html
        format.json { render json: @goal_data }
      end

    end

    def new
      @goal = Goal.new
    end

    def create
      if !(Goal.where(:user_id => current_user.id).present?)
        current_user.goals.create(goal_params)
        redirect_to dashboards_path
      else
        flash[:alert] = 'Only permitted to store one goal'
        redirect_to dashboards_path
      end

    end

    def goal_params
      params.require(:goal).permit(:amount, :name, :start_date, :target_date)
    end


end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController

  before_action :authenticate_user!

  def index

    @income_data = Income.where(user_id: current_user.id)

    respond_to do |format|
      format.html
      format.json { render json: @income_data }
    end

  end

  def new
    @income = Income.new
  end

  def create

    current_user.incomes.create(income_params)

    redirect_to dashboards_path
  end

  private

  def income_params
    params.require(:income).permit(:amount, :name, :date, :current_user)
  end


end

app/controllers/projections_controller.rb
class ProjectionsController < ApplicationController

  before_action :authenticate_user!

  def index

    @projection_data = Projection.where(user_id: current_user.id)

    respond_to do |format|
      format.html
      format.json { render json: @projection_data }
    end

  end

  def new
    @projection = Projection.new
  end

  def create
    if !(Projection.where(:user_id => current_user.id).present?)
      current_user.projections.create(projection_params)
    else
      flash[:alert] = 'Only permitted to store one projection'
    end
    redirect_to dashboards_path
  end

  private

  def projection_params
    params.require(:projection).permit(:projected_monthly_income, :projected_monthly_expenditure, :start_date )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/helpers/goal_helper.rb
module GoalHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
  

end

app/helpers/projections_helper.rb
module ProjectionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MillionaireMachine</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "http://code.highcharts.com/highcharts.js" %>

  </head>
  <body>

<div class="user_signed_in">
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <a href="/dashboards" class="pull-left"><img src="/images/logo.png" height="70px" width="70px"></a>
    <div class="sign_in_buttons">
      <% if user_signed_in? %>
      <div class="user_welcome">
        Welcome <%= current_user.email %>
      </div>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      <%= link_to "Add Income", new_income_path %>
      <%= link_to "Add Expenditure", new_expenditure_path %>
      <%= link_to "Add Projection", new_projection_path %>
      <%= link_to "Add Goal", new_goal_path %>

      <% else %>
      <%= link_to "Sign in", new_user_session_path %>
      <%= link_to "Sign up", new_user_registration_path %>

    <% end %>


  </div>
  </div>

</div>
    <%= alert %>
    <!-- <%= notice %> -->
    <%= yield %>
    <footer class="footer">
            © 2017 Copyright by Million-Machine Team |
            <a href="https://github.com/thesedatedprince/millionaire-machine" target="_blank">GitHub</a>



        </footer>

  </body>
</html>